//! Ordered system languages from a native catalog. No caller-supplied locale tag setter.
use makepad_strict_json::Value;
pub const PAGE_SIZE:u32=20;
pub const MAX_CURRENT:usize=128;
#[derive(serde::Serialize, Clone,Debug,PartialEq,Eq,Hash)]pub struct SystemLanguageKey(String);
impl SystemLanguageKey{pub fn wire(&self)->&str{&self.0}pub(crate) fn decode(value:&Value)->Option<Self>{let s=value.as_str()?;(s.len()==64&&s.bytes().all(|c|c.is_ascii_digit()||(b'a'..=b'f').contains(&c))).then(||Self(s.into()))}}
#[derive(serde::Serialize, Clone,Debug,Default,PartialEq,Eq)]pub struct SystemLanguageRead{pub key:Option<SystemLanguageKey>,pub parent:Option<SystemLanguageKey>,pub query:String,pub offset:u32}
impl SystemLanguageRead{pub fn valid(&self)->bool{self.query.chars().count()<=80&&!self.query.chars().any(char::is_control)&&self.offset<4096&&self.offset%PAGE_SIZE==0&&(self.key.is_some()||(self.parent.is_none()&&self.offset==0))}}
#[derive(serde::Serialize, Clone,Debug,PartialEq,Eq)]pub enum SystemLanguageRequest{Snapshot(SystemLanguageRead),Apply{key:SystemLanguageKey,order:Vec<SystemLanguageKey>}}
impl SystemLanguageRequest{pub fn valid(&self)->bool{match self{Self::Snapshot(read)=>read.valid(),Self::Apply{order,..}=>!order.is_empty()&&order.len()<=MAX_CURRENT&&order.iter().enumerate().all(|(index,key)|!order[..index].contains(key))}}}
#[derive(serde::Serialize, Clone,Copy,Debug,PartialEq,Eq)]pub enum SystemLanguageAvailability{Available,Restricted,Unavailable,Stale}
#[derive(serde::Serialize, Clone,Copy,Debug,PartialEq,Eq)]pub enum SystemLanguageReason{None,Locked,Policy,Unavailable,InvalidCatalog,Expired,Changed}
impl SystemLanguageReason{pub fn label(self)->&'static str{match self{Self::None=>"",Self::Locked=>"Unlock the device to change system languages.",Self::Policy=>"Android policy prevents changing system languages.",Self::Unavailable=>"System language controls are unavailable on this installation.",Self::InvalidCatalog=>"Android’s language list could not be read completely. Open Android language settings to continue.",Self::Expired=>"These language choices expired. Refresh and review the order again.",Self::Changed=>"The system language list, regional preferences, or available choices changed. Your draft is preserved; cancel it and refresh to review the current list."}}}
#[derive(serde::Serialize, Clone,Copy,Debug,PartialEq,Eq)]pub enum SystemLanguageLevel{Language,Region,Numbering}
impl SystemLanguageLevel{fn decode(v:&Value)->Option<Self>{Some(match v.as_str()?{"language"=>Self::Language,"region"=>Self::Region,"numbering"=>Self::Numbering,_=>return None})}pub fn label(self)->&'static str{match self{Self::Language=>"Languages",Self::Region=>"Regions",Self::Numbering=>"Numbering systems"}}}
#[derive(serde::Serialize, Clone,Copy,Debug,PartialEq,Eq)]pub enum SystemLanguageKind{Open,Select}
#[derive(serde::Serialize, Clone,Debug,PartialEq,Eq)]pub struct SystemLanguage{pub target:SystemLanguageKey,pub tag:String,pub label:String,pub native_label:String,pub translated:bool}
#[derive(serde::Serialize, Clone,Debug,PartialEq,Eq)]pub struct SystemLanguageRow{pub target:SystemLanguageKey,pub tag:String,pub label:String,pub secondary:Option<String>,pub kind:SystemLanguageKind,pub translated:bool,pub suggested:bool}
#[derive(serde::Serialize, Clone,Debug)]pub struct SystemLanguageSnapshot{
    pub request_id:i64,pub availability:SystemLanguageAvailability,pub reason:SystemLanguageReason,pub key:Option<SystemLanguageKey>,pub can_apply:bool,pub current:Option<Vec<SystemLanguage>>,pub parent:Option<SystemLanguageKey>,pub parent_label:Option<String>,pub level:SystemLanguageLevel,pub query:String,pub offset:u32,pub total:u32,pub rows:Vec<SystemLanguageRow>,
}
fn text(v:&Value)->Option<String>{let s=v.as_str()?;(!s.trim().is_empty()&&s.chars().count()<=256&&!s.chars().any(char::is_control)).then(||s.into())}
fn optional<T>(value:Option<&Value>,decode:impl FnOnce(&Value)->Option<T>)->Option<Option<T>>{match value{None|Some(Value::Null)=>Some(None),Some(v)=>decode(v).map(Some)}}
impl SystemLanguageSnapshot{
    pub fn decode(v:&Value)->Option<Self>{
        if v.get("schema")?.as_i64()?!=1||v.get("page_size")?.as_i64()?!=PAGE_SIZE as i64{return None;}
        let availability=match v.get("availability")?.as_str()?{"available"=>SystemLanguageAvailability::Available,"restricted"=>SystemLanguageAvailability::Restricted,"unavailable"=>SystemLanguageAvailability::Unavailable,"stale"=>SystemLanguageAvailability::Stale,_=>return None};
        let reason=match v.get("reason")?.as_str()?{"none"=>SystemLanguageReason::None,"locked"=>SystemLanguageReason::Locked,"policy"=>SystemLanguageReason::Policy,"service_unavailable"=>SystemLanguageReason::Unavailable,"invalid_catalog"=>SystemLanguageReason::InvalidCatalog,"catalog_expired"=>SystemLanguageReason::Expired,"target_changed"=>SystemLanguageReason::Changed,_=>return None};
        let current=optional(v.get("current"),|v|{let rows=v.as_arr()?;if rows.is_empty()||rows.len()>MAX_CURRENT{return None;}let mut result=Vec::<SystemLanguage>::new();for row in rows{let language=SystemLanguage{target:SystemLanguageKey::decode(row.get("target")?)?,tag:text(row.get("tag")?)?,label:text(row.get("label")?)?,native_label:text(row.get("native_label")?)?,translated:row.get("translated")?.as_bool()?};if result.iter().any(|r|r.target==language.target||r.tag==language.tag){return None;}result.push(language);}Some(result)})?;
        let mut rows=Vec::<SystemLanguageRow>::new();for raw in v.get("rows")?.as_arr()?{let row=SystemLanguageRow{target:SystemLanguageKey::decode(raw.get("target")?)?,tag:text(raw.get("tag")?)?,label:text(raw.get("label")?)?,secondary:optional(raw.get("secondary"),text)?,kind:match raw.get("kind")?.as_str()?{"open"=>SystemLanguageKind::Open,"select"=>SystemLanguageKind::Select,_=>return None},translated:raw.get("translated")?.as_bool()?,suggested:raw.get("suggested")?.as_bool()?};if rows.iter().any(|r|r.target==row.target)||current.as_ref().is_some_and(|c|c.iter().any(|r|r.target==row.target)){return None;}rows.push(row);}
        let n=|name:&str,max:i64|v.get(name)?.as_i64().filter(|n|*n>=0&&*n<=max).map(|n|n as u32);
        let out=Self{request_id:v.get("request_id")?.as_i64().filter(|n|*n>0)?,availability,reason,key:optional(v.get("key"),SystemLanguageKey::decode)?,can_apply:v.get("can_apply")?.as_bool()?,current,parent:optional(v.get("parent"),SystemLanguageKey::decode)?,parent_label:optional(v.get("parent_label"),text)?,level:SystemLanguageLevel::decode(v.get("level")?)?,query:v.get("query")?.as_str()?.into(),offset:n("offset",4095)?,total:n("total",4096)?,rows};
        if out.query.chars().count()>80||out.query.chars().any(char::is_control)||out.offset%PAGE_SIZE!=0{return None;}
        if availability==SystemLanguageAvailability::Available{
            if out.key.is_none()||out.current.is_none()||reason!=SystemLanguageReason::None||out.parent.is_some()!=out.parent_label.is_some()||out.parent.is_none()!=(out.level==SystemLanguageLevel::Language){return None;}
            if out.offset>=out.total&&(out.offset!=0||out.total!=0){return None;}if out.rows.len()!=(out.total-out.offset).min(PAGE_SIZE)as usize{return None;}
        }else if out.key.is_some()||out.current.is_some()||out.parent.is_some()||out.parent_label.is_some()||out.can_apply||out.offset!=0||out.total!=0||!out.rows.is_empty(){return None;}
        Some(out)
    }
    pub fn matches(&self,read:&SystemLanguageRead)->bool{self.query==read.query&&(self.availability!=SystemLanguageAvailability::Available||(self.parent==read.parent&&(read.key.is_none()||self.key==read.key)&&(self.offset==read.offset||(self.offset==0&&read.offset>=self.total))))}
    pub fn clear_actions(&mut self){self.can_apply=false;}
}

/// Local, fully reviewable order; polling never replaces edits or repairs stale authority.
#[derive(serde::Serialize, Clone,Debug)]pub struct SystemLanguageDraft{pub key:SystemLanguageKey,pub original:Vec<SystemLanguage>,pub order:Vec<SystemLanguage>,pub submitted:bool}
impl SystemLanguageDraft{
    pub fn begin(snapshot:&SystemLanguageSnapshot)->Option<Self>{if snapshot.availability!=SystemLanguageAvailability::Available||!snapshot.can_apply{return None;}let current=snapshot.current.clone()?;Some(Self{key:snapshot.key.clone()?,original:current.clone(),order:current,submitted:false})}
    pub fn changed(&self)->bool{self.order!=self.original}
    pub fn reorder(&mut self,index:usize,next:usize)->bool{if self.submitted||index>=self.order.len()||next>=self.order.len()||index==next{return false;}let row=self.order.remove(index);self.order.insert(next,row);true}
    pub fn remove(&mut self,index:usize)->bool{if self.submitted||self.order.len()<=1||index>=self.order.len(){return false;}self.order.remove(index);true}
    pub fn add(&mut self,row:&SystemLanguageRow)->bool{if self.submitted||row.kind!=SystemLanguageKind::Select||self.order.len()>=MAX_CURRENT||self.order.iter().any(|r|r.tag==row.tag||r.target==row.target){return false;}self.order.push(SystemLanguage{target:row.target.clone(),tag:row.tag.clone(),label:row.secondary.clone().unwrap_or_else(||row.label.clone()),native_label:row.label.clone(),translated:row.translated});true}
    pub fn current(&self,snapshot:&SystemLanguageSnapshot)->bool{snapshot.availability==SystemLanguageAvailability::Available&&snapshot.can_apply&&snapshot.key.as_ref()==Some(&self.key)&&snapshot.current.as_ref()==Some(&self.original)}
    pub fn request(&self,snapshot:&SystemLanguageSnapshot)->Option<SystemLanguageRequest>{if self.submitted||!self.changed()||!self.current(snapshot){return None;}let request=SystemLanguageRequest::Apply{key:self.key.clone(),order:self.order.iter().map(|r|r.target.clone()).collect()};request.valid().then_some(request)}
    pub fn confirmed(&self,snapshot:&SystemLanguageSnapshot)->bool{self.submitted&&snapshot.current.as_ref().is_some_and(|current|current.len()==self.order.len()&&current.iter().zip(&self.order).all(|(a,b)|a.tag==b.tag))}
    pub fn changes_primary(&self)->bool{self.order.first().map(|r|&r.tag)!=self.original.first().map(|r|&r.tag)}
}

#[cfg(test)]pub(crate) mod tests{
    use super::*;
    pub fn snapshot(id:i64)->Value{makepad_strict_json::parse(format!(r#"{{"schema":1,"page_size":20,"request_id":{id},"availability":"available","reason":"none","key":"{:064x}","can_apply":true,"current":[{{"target":"{:064x}","tag":"en-US-u-hc-h23","label":"English","native_label":"English","translated":true}},{{"target":"{:064x}","tag":"zz-Latn-ZZ-u-nu-latn","label":"Custom language","native_label":"Custom language","translated":false}}],"parent":null,"level":"language","query":"","offset":0,"total":2,"rows":[{{"target":"{:064x}","tag":"fr","label":"Français","secondary":"French","kind":"open","translated":true,"suggested":false}},{{"target":"{:064x}","tag":"ar-EG-u-hc-h23-nu-latn","label":"العربية","secondary":"Arabic (Egypt)","kind":"select","translated":true,"suggested":true}}]}}"#,1,2,3,4,5).as_bytes()).unwrap()}
    #[test]fn reviewed_order_preserves_custom_tags_and_last_language(){let s=SystemLanguageSnapshot::decode(&snapshot(1)).unwrap();let mut draft=SystemLanguageDraft::begin(&s).unwrap();assert!(!draft.add(&s.rows[0]));assert!(draft.add(&s.rows[1]));assert!(draft.reorder(2,0));assert!(draft.changes_primary());assert_eq!(draft.order[2].tag,"zz-Latn-ZZ-u-nu-latn");assert!(draft.request(&s).is_some());assert!(draft.remove(2));assert!(draft.remove(1));assert!(!draft.remove(0));assert_eq!(draft.order[0].tag,"ar-EG-u-hc-h23-nu-latn");}
    #[test]fn stale_or_submitted_draft_keeps_order_without_write_authority(){let mut s=SystemLanguageSnapshot::decode(&snapshot(1)).unwrap();let mut draft=SystemLanguageDraft::begin(&s).unwrap();draft.reorder(1,0);let edited=draft.order.clone();s.clear_actions();assert!(draft.request(&s).is_none());assert_eq!(draft.order,edited);s.can_apply=true;draft.submitted=true;assert!(draft.request(&s).is_none());assert!(!draft.confirmed(&s));s.current=Some(draft.order.clone());assert!(draft.confirmed(&s));assert!(!draft.add(&s.rows[1]));}
    #[test]fn malformed_catalog_is_unavailable_not_an_empty_current_list(){use crate::settings_updates::tests::field;let mut v=snapshot(1);field(&mut v,"current",Value::Arr(vec![]));assert!(SystemLanguageSnapshot::decode(&v).is_none());let mut v=snapshot(1);field(&mut v,"total",Value::Int(3));assert!(SystemLanguageSnapshot::decode(&v).is_none());let mut v=snapshot(1);field(&mut v,"availability",makepad_strict_json::s("unavailable"));assert!(SystemLanguageSnapshot::decode(&v).is_none());}
    #[test]fn reviewed_order_and_catalog_bounds_are_finite(){let s=SystemLanguageSnapshot::decode(&snapshot(1)).unwrap();let key=s.key.clone().unwrap();let target=s.current.as_ref().unwrap()[0].target.clone();assert!(!SystemLanguageRequest::Apply{key:key.clone(),order:vec![]}.valid());assert!(!SystemLanguageRequest::Apply{key:key.clone(),order:vec![target.clone(),target]}.valid());let mut read=SystemLanguageRead::default();read.query="字".repeat(81);assert!(!read.valid());read.query="😀".repeat(80);assert!(read.valid());read.query.push('😀');assert!(!read.valid());read.query.clear();read.offset=20;assert!(!read.valid());read.key=Some(key);assert!(read.valid());read.offset=4100;assert!(!read.valid());}
}
