//! @generated by tools/native_apps.py from native-apps.json: do not edit;
//! change the manifest and run the script (ADR 0004 §1).
//!
//! The native apps this shell can link, in link order: the modules
//! `apps::linked_modules()` pushes under each app's feature, and the
//! hosting each app gets by default on each target.

use makepad_app_module::AppModule;

/// An app's hosting on one target, as the manifest declares it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Hosting {
    /// In the shell's process: a splash isolate per instance.
    Module,
    /// Its own process (`bin`), connected to the shell's hub.
    Process,
    /// Its own process on a Vulkan build in a Wayland session; in the
    /// shell's process otherwise.
    ProcessIfVulkan,
}

/// Who shows the person a tool's live confirmation (ADR 0004 §8).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Confirm {
    /// The shell's own sheet (the assistant's confirm card).
    Host,
    /// The owning app's own sheet.
    App,
}

/// How the shell treats one of an app's assistant tools.
#[derive(Debug)]
pub struct ToolPolicy {
    pub tool: &'static str,
    pub confirm: Confirm,
    /// Whether a standing rule may answer its confirmation; `false`:
    /// only the person, live, every time (outside developer mode).
    pub auto_approvable: bool,
}

/// One `native-apps.json` entry, as far as the shell reads it.
#[derive(Debug)]
pub struct NativeApp {
    pub id: &'static str,
    /// The shell's Cargo feature that links it.
    pub feature: &'static str,
    /// The binary a process-hosted instance runs.
    pub bin: Option<&'static str>,
    pub macos: Hosting,
    pub windows: Hosting,
    pub linux: Hosting,
    pub android: Hosting,
    pub ios: Hosting,
    pub ohos: Hosting,
    pub wasm: Hosting,
    /// The `octos.*` services its reviewed entry grants it.
    pub octos: &'static [&'static str],
    /// Its assistant tools' confirmation rules (`agent.tool_policy`).
    pub tools: &'static [ToolPolicy],
}

pub const APPS: &[NativeApp] = &[
    NativeApp {
        id: "rinx",
        feature: "app-rinx",
        bin: None,
        macos: Hosting::Module,
        windows: Hosting::Module,
        linux: Hosting::Module,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &["octos.session.open", "octos.session.history", "octos.turn.start", "octos.turn.interrupt"],
        tools: &[],
    },
    NativeApp {
        id: "reference",
        feature: "app-reference",
        bin: Some("octosense-reference"),
        macos: Hosting::Module,
        windows: Hosting::Module,
        linux: Hosting::Module,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &[],
        tools: &[],
    },
    NativeApp {
        id: "liyu",
        feature: "app-liyu",
        bin: Some("octosense-liyu"),
        macos: Hosting::Process,
        windows: Hosting::Process,
        linux: Hosting::ProcessIfVulkan,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &[],
        tools: &[],
    },
    NativeApp {
        id: "sheets",
        feature: "app-sheets",
        bin: Some("sheets"),
        macos: Hosting::Module,
        windows: Hosting::Module,
        linux: Hosting::Module,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &[],
        tools: &[],
    },
    NativeApp {
        id: "terminal",
        feature: "app-terminal",
        bin: Some("terminal"),
        macos: Hosting::Process,
        windows: Hosting::Process,
        linux: Hosting::ProcessIfVulkan,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &[],
        tools: &[
            ToolPolicy { tool: "run", confirm: Confirm::Host, auto_approvable: false },
        ],
    },
    NativeApp {
        id: "appcard",
        feature: "app-appcard",
        bin: None,
        macos: Hosting::Module,
        windows: Hosting::Module,
        linux: Hosting::Module,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &[],
        tools: &[],
    },
    NativeApp {
        id: "apphub",
        feature: "app-hub",
        bin: None,
        macos: Hosting::Module,
        windows: Hosting::Module,
        linux: Hosting::Module,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &[],
        tools: &[],
    },
];

impl NativeApp {
    /// Its hosting on the target this shell is built for.
    pub const fn on_this_target(&self) -> Hosting {
        if cfg!(target_arch = "wasm32") {
            self.wasm
        } else if cfg!(target_os = "android") {
            self.android
        } else if cfg!(target_os = "ios") {
            self.ios
        } else if cfg!(target_env = "ohos") {
            self.ohos
        } else if cfg!(target_os = "macos") {
            self.macos
        } else if cfg!(target_os = "windows") {
            self.windows
        } else {
            self.linux
        }
    }
}

impl NativeApp {
    /// The rule for one of its tools, if the manifest sets one.
    pub fn tool(&self, name: &str) -> Option<&'static ToolPolicy> {
        self.tools.iter().find(|rule| rule.tool == name)
    }
}

/// The manifest entry for an app id.
pub fn find(id: &str) -> Option<&'static NativeApp> {
    APPS.iter().find(|app| app.id == id)
}

/// Push the native modules this build links, in manifest order.
#[allow(unused_variables)]
pub fn link(out: &mut Vec<&'static dyn AppModule>) {
    #[cfg(feature = "app-rinx")]
    out.push(&rinx::module::RINX_MODULE);
    #[cfg(any(feature = "app-reference", native_mobile))]
    out.push(&octosense_reference::REFERENCE_MODULE);
    #[cfg(feature = "app-liyu")]
    out.push(&octosense_liyu::LIYU_MODULE);
    #[cfg(any(feature = "app-sheets", native_mobile))]
    out.push(&makepad_sheets::SHEETS_MODULE);
    #[cfg(feature = "app-terminal")]
    out.push(&makepad_terminal::TERMINAL_MODULE);
    #[cfg(feature = "app-appcard")]
    out.push(&octosense_appcard::APPCARD_MODULE);
    #[cfg(any(feature = "app-hub", native_mobile))]
    {
        out.push(&octosense_app_hub_app::APP_HUB_MODULE);
        out.push(&octosense_app_hub_app::CARD_MODULE);
    }
}
