#!/usr/bin/env python3
"""Generate every place that links OctoSense's native apps (Python 3.9+).

Native apps (Rust crates the shell links: App Hub, Rinx, Terminal, and the
opt-in Sheets, Reference, AppCard) are declared once, in `native-apps.json`
at the repository root (ADR 0004 §1). This script writes what follows from
it, each between `# BEGIN native-apps: <block>` and `# END native-apps:
<block>` markers:

  Cargo.toml             the app crates' pins in [workspace.dependencies]
                         ("pins") and the [patch] entries that resolve a
                         git source to its `local` checkout ("patch <git>")
  crates/shell/Cargo.toml the optional dependencies ("deps"), the ones
                         native mobile targets link without flags ("mobile
                         deps") and the `app-<id>` / `mobile-apps` features
                         ("features")
  desktop/Cargo.toml,    the package's default features and the forwarded
  phone/Cargo.toml       `app-<id>` / `mobile-apps` features ("features")

and the whole of `crates/shell/src/native_apps.rs`: what `linked_modules()`
pushes under which feature, and each app's hosting per target (the default
the shell uses when the person has not switched an app).

It refuses `process` hosting on mobile or wasm targets, plain `process` on
Linux (non-Vulkan Linux runs every app in-process: `process-if-vulkan`),
`process` without a `bin`, and two revisions of one git repository in the
root pins. After a write, Cargo.lock is brought in step by cargo itself
(`cargo update -p` for a pin that changed, then `cargo metadata`); --no-lock
skips that.

  python3 tools/native_apps.py            # regenerate after editing the manifest
  python3 tools/native_apps.py --check    # CI: exit 1 when anything drifted
"""
import argparse
import json
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = "native-apps.json"
RUST_FILE = "crates/shell/src/native_apps.rs"
PACKAGES = {"desktop": "desktop/Cargo.toml", "phone": "phone/Cargo.toml"}

TARGETS = ("macos", "windows", "linux", "android", "ios", "ohos")
# Targets without child processes (`host::processes_available()` is false).
MODULE_ONLY = ("android", "ios", "ohos", "wasm")
HOSTINGS = ("module", "process", "process-if-vulkan")
# How a package links an app: in its default features, in its `mobile-apps`
# set, only when asked for, or not at all.
SHELL_LINKS = ("default", "mobile-apps", "opt-in", "off")
# Every standard shell build runs the octos kernel as a shell service.
BASE_DEFAULT = ["octos-core"]
APP_KEYS = {"id", "feature", "crate", "source", "module", "bin", "default_features", "crate_features",
            "implies", "hosting", "shells", "native_mobile", "sandbox", "storage", "agent"}
REQUIRED_KEYS = APP_KEYS - {"feature"}
NOTE = "(generated by tools/native_apps.py from native-apps.json; do not edit)"


class ManifestError(Exception):
    pass


def note(message):
    print(f"native-apps: {message}", file=sys.stderr)


# --- The manifest ----------------------------------------------------------


def load(root):
    path = Path(root) / MANIFEST
    try:
        data = json.loads(path.read_text())
    except (OSError, ValueError) as error:
        raise ManifestError(f"{MANIFEST}: {error}")
    return validate(data)


def validate(data):
    """The apps, checked; every problem is reported at once."""
    problems = []
    if not isinstance(data, dict) or data.get("schema") != 1 or not isinstance(data.get("apps"), list):
        raise ManifestError(f'{MANIFEST}: expected {{"schema": 1, "apps": [...]}}')
    seen, features, crates = set(), set(), set()
    for index, app in enumerate(data["apps"]):
        where = f"apps[{index}]"
        if not isinstance(app, dict):
            problems.append(f"{where}: not an object")
            continue
        where = f"{app.get('id', where)}"
        missing = sorted(REQUIRED_KEYS - set(app))
        unknown = sorted(set(app) - APP_KEYS)
        if missing:
            problems.append(f"{where}: missing {', '.join(missing)}")
        if unknown:
            problems.append(f"{where}: unknown {', '.join(unknown)}")
        if missing:
            continue
        ident = app["id"]
        if not isinstance(ident, str) or not re.fullmatch(r"[a-z][a-z0-9-]*", ident):
            problems.append(f"{where}: id must be lowercase letters, digits and '-'")
        if ident in seen:
            problems.append(f"{where}: duplicate id")
        seen.add(ident)
        feature = feature_of(app)
        if feature in features:
            problems.append(f"{where}: duplicate feature {feature}")
        features.add(feature)
        if app["crate"] in crates:
            problems.append(f"{where}: duplicate crate {app['crate']}")
        crates.add(app["crate"])
        source = app["source"]
        if not isinstance(source, dict):
            problems.append(f"{where}: source must be an object")
        elif "path" in source:
            if set(source) != {"path"}:
                problems.append(f"{where}: a path source has only 'path'")
        elif set(source) != {"git", "rev", "local"}:
            problems.append(f"{where}: source is {{git, rev, local}} or {{path}}")
        elif not re.fullmatch(r"[0-9a-f]{40}", str(source["rev"])):
            problems.append(f"{where}: source.rev must be a full commit id")
        if not modules_of(app) or not all(re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*(::[A-Za-z_][A-Za-z0-9_]*)+", m) for m in modules_of(app)):
            problems.append(f"{where}: module must be a Rust path (or a list of them)")
        if app["bin"] is not None and not (isinstance(app["bin"], str) and app["bin"]):
            problems.append(f"{where}: bin must be a binary name or null")
        if not isinstance(app["default_features"], bool):
            problems.append(f"{where}: default_features must be true or false")
        for key in ("crate_features", "implies"):
            if not isinstance(app[key], list) or not all(isinstance(x, str) for x in app[key]):
                problems.append(f"{where}: {key} must be a list of strings")
        hosting = app["hosting"]
        if not isinstance(hosting, dict):
            problems.append(f"{where}: hosting must be an object")
        else:
            for target in TARGETS:
                if target not in hosting:
                    problems.append(f"{where}: hosting.{target} is missing")
            for target, value in hosting.items():
                if target not in TARGETS + ("wasm",):
                    problems.append(f"{where}: hosting.{target}: unknown target")
                elif value not in HOSTINGS:
                    problems.append(f"{where}: hosting.{target}: {value!r} is not one of {', '.join(HOSTINGS)}")
                elif value != "module" and target in MODULE_ONLY:
                    problems.append(f"{where}: hosting.{target}: {target} has no processes; only 'module'")
                elif value == "process" and target == "linux":
                    problems.append(f"{where}: hosting.linux: 'process' would run without Vulkan+Wayland; "
                                    "use 'process-if-vulkan' (ADR 0004 §2)")
                elif value != "module" and not app["bin"]:
                    problems.append(f"{where}: hosting.{target}: '{value}' needs a bin")
        shells = app["shells"]
        if not isinstance(shells, dict) or set(shells) != set(PACKAGES):
            problems.append(f"{where}: shells must name {', '.join(PACKAGES)}")
        else:
            for shell, value in shells.items():
                if value not in SHELL_LINKS:
                    problems.append(f"{where}: shells.{shell}: {value!r} is not one of {', '.join(SHELL_LINKS)}")
        if app["native_mobile"] not in ("always", "feature"):
            problems.append(f"{where}: native_mobile must be 'always' or 'feature'")
        for key in ("sandbox", "storage", "agent"):
            if not isinstance(app[key], dict):
                problems.append(f"{where}: {key} must be an object")
        if isinstance(app["agent"], dict) and not isinstance(app["agent"].get("octos"), list):
            problems.append(f"{where}: agent.octos must be a list")
        if isinstance(app["agent"], dict):
            problems += [f"{where}: {p}" for p in tool_policy_problems(app["agent"].get("tool_policy", {}))]
    if problems:
        raise ManifestError(f"{MANIFEST}:\n  " + "\n  ".join(problems))
    return data["apps"]


def tool_policy_problems(policy):
    """`agent.tool_policy`: {tool: {"confirm": "host"|"app", "auto_approvable": bool}}
    (ADR 0004 §8). A tool the shell confirms live and no standing rule may
    approve is `confirm: host`, `auto_approvable: false`."""
    if not isinstance(policy, dict):
        return ["agent.tool_policy must be an object"]
    problems = []
    for tool, rule in policy.items():
        if not re.fullmatch(r"[a-z][a-z0-9_]*", tool):
            problems.append(f"agent.tool_policy: {tool!r} is not a tool name")
        elif not isinstance(rule, dict) or set(rule) != {"confirm", "auto_approvable"}:
            problems.append(f"agent.tool_policy.{tool}: needs exactly confirm and auto_approvable")
        elif rule["confirm"] not in ("host", "app"):
            problems.append(f"agent.tool_policy.{tool}.confirm must be 'host' or 'app'")
        elif not isinstance(rule["auto_approvable"], bool):
            problems.append(f"agent.tool_policy.{tool}.auto_approvable must be true or false")
    return problems


def feature_of(app):
    return app.get("feature") or f"app-{app['id']}"


def modules_of(app):
    module = app["module"]
    if isinstance(module, str):
        return [module]
    if isinstance(module, list) and all(isinstance(m, str) for m in module):
        return module
    return []


def same_git(a, b):
    def norm(url):
        url = url.strip().rstrip("/")
        return (url[:-4] if url.endswith(".git") else url).lower()
    return norm(a) == norm(b)


# --- Rendering -------------------------------------------------------------


def s(value):
    """A TOML basic string (JSON's escaping is a subset of TOML's)."""
    return json.dumps(value)


def toml_list(values):
    return "[" + ", ".join(s(v) for v in values) + "]"


def pin_line(app):
    source = app["source"]
    if "path" in source:
        fields = [f"path = {s(source['path'])}"]
    else:
        fields = [f"git = {s(source['git'])}", f"rev = {s(source['rev'])}"]
    if not app["default_features"]:
        fields.append("default-features = false")
    if app["crate_features"]:
        fields.append(f"features = {toml_list(app['crate_features'])}")
    return f"{app['crate']} = {{ {', '.join(fields)} }}"


def patch_urls(apps):
    """The git sources some app resolves to a local checkout, in order."""
    urls = []
    for app in apps:
        source = app["source"]
        if source.get("local") and not any(same_git(u, source["git"]) for u in urls):
            urls.append(source["git"])
    return urls


def root_blocks(apps):
    blocks = {"pins": [pin_line(app) for app in apps]}
    for url in patch_urls(apps):
        blocks[f"patch {url}"] = [
            f"{app['crate']} = {{ path = {s(app['source']['local'])} }}"
            for app in apps
            if app["source"].get("local") and same_git(app["source"]["git"], url)
        ]
    return blocks


def in_mobile_apps(app):
    return app["shells"]["phone"] in ("default", "mobile-apps")


def shell_blocks(apps):
    def dep(app, optional):
        fields = ["workspace = true"]
        if app["crate_features"]:
            fields.append(f"features = {toml_list(app['crate_features'])}")
        if optional:
            fields.append("optional = true")
        return f"{app['crate']} = {{ {', '.join(fields)} }}"

    mobile_apps = [feature_of(app) for app in apps if in_mobile_apps(app)] + BASE_DEFAULT
    features = [f"mobile-apps = {toml_list(mobile_apps)}"]
    features += [f"{feature_of(app)} = {toml_list(['dep:' + app['crate']] + app['implies'])}" for app in apps]
    return {
        "deps": [dep(app, True) for app in apps],
        "mobile deps": [dep(app, False) for app in apps if app["native_mobile"] == "always"],
        "features": features,
    }


def optional_deps(cargo_toml):
    """The optional dependencies a package's own [dependencies] declares."""
    names, table = set(), None
    for line in cargo_toml.splitlines():
        stripped = line.strip()
        if stripped.startswith("["):
            table = stripped
            continue
        if table == "[dependencies]":
            match = re.match(r"([A-Za-z0-9_-]+)\s*=\s*\{(.*)\}", stripped)
            if match and re.search(r"\boptional\s*=\s*true\b", match.group(2)):
                names.add(match.group(1))
    return names


def package_block(apps, shell, cargo_toml):
    """A package's default and forwarded features. An app whose crate the
    package also depends on itself (optionally) turns that dependency on."""
    own = optional_deps(cargo_toml)
    linked = [app for app in apps if app["shells"][shell] != "off"]
    default = BASE_DEFAULT + [feature_of(app) for app in linked if app["shells"][shell] == "default"]
    mobile = [feature_of(app) for app in linked if in_mobile_apps(app) and app["crate"] in own]
    lines = [f"default = {toml_list(default)}",
             f"mobile-apps = {toml_list(mobile + ['octosense-shell/mobile-apps'])}"]
    for app in linked:
        deps = [f"dep:{app['crate']}"] if app["crate"] in own else []
        lines.append(f"{feature_of(app)} = {toml_list(deps + ['octosense-shell/' + feature_of(app)])}")
    return {"features": lines}


def rust_hosting(value):
    return {"module": "Hosting::Module", "process": "Hosting::Process",
            "process-if-vulkan": "Hosting::ProcessIfVulkan"}[value]


def render_rust(apps):
    out = [
        f"//! @generated by tools/native_apps.py from native-apps.json: do not edit;",
        "//! change the manifest and run the script (ADR 0004 §1).",
        "//!",
        "//! The native apps this shell can link, in link order: the modules",
        "//! `apps::linked_modules()` pushes under each app's feature, and the",
        "//! hosting each app gets by default on each target.",
        "",
        "use makepad_app_module::AppModule;",
        "",
        "/// An app's hosting on one target, as the manifest declares it.",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub enum Hosting {",
        "    /// In the shell's process: a splash isolate per instance.",
        "    Module,",
        "    /// Its own process (`bin`), connected to the shell's hub.",
        "    Process,",
        "    /// Its own process on a Vulkan build in a Wayland session; in the",
        "    /// shell's process otherwise.",
        "    ProcessIfVulkan,",
        "}",
        "",
        "/// Who shows the person a tool's live confirmation (ADR 0004 §8).",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub enum Confirm {",
        "    /// The shell's own sheet (the assistant's confirm card).",
        "    Host,",
        "    /// The owning app's own sheet.",
        "    App,",
        "}",
        "",
        "/// How the shell treats one of an app's assistant tools.",
        "#[derive(Debug)]",
        "pub struct ToolPolicy {",
        "    pub tool: &'static str,",
        "    pub confirm: Confirm,",
        "    /// Whether a standing rule may answer its confirmation; `false`:",
        "    /// only the person, live, every time (outside developer mode).",
        "    pub auto_approvable: bool,",
        "}",
        "",
        "/// One `native-apps.json` entry, as far as the shell reads it.",
        "#[derive(Debug)]",
        "pub struct NativeApp {",
        "    pub id: &'static str,",
        "    /// The shell's Cargo feature that links it.",
        "    pub feature: &'static str,",
        "    /// The binary a process-hosted instance runs.",
        "    pub bin: Option<&'static str>,",
        "    pub macos: Hosting,",
        "    pub windows: Hosting,",
        "    pub linux: Hosting,",
        "    pub android: Hosting,",
        "    pub ios: Hosting,",
        "    pub ohos: Hosting,",
        "    pub wasm: Hosting,",
        "    /// The `octos.*` services its reviewed entry grants it.",
        "    pub octos: &'static [&'static str],",
        "    /// Its assistant tools' confirmation rules (`agent.tool_policy`).",
        "    pub tools: &'static [ToolPolicy],",
        "}",
        "",
        "pub const APPS: &[NativeApp] = &[",
    ]
    for app in apps:
        hosting = dict(app["hosting"])
        hosting.setdefault("wasm", "module")
        bin_value = f"Some({s(app['bin'])})" if app["bin"] else "None"
        octos = ", ".join(s(x) for x in app["agent"]["octos"])
        out.append("    NativeApp {")
        out.append(f"        id: {s(app['id'])},")
        out.append(f"        feature: {s(feature_of(app))},")
        out.append(f"        bin: {bin_value},")
        for target in TARGETS + ("wasm",):
            out.append(f"        {target}: {rust_hosting(hosting[target])},")
        out.append(f"        octos: &[{octos}],")
        policy = app["agent"].get("tool_policy", {})
        if policy:
            out.append("        tools: &[")
            for tool, rule in policy.items():
                confirm = "Confirm::Host" if rule["confirm"] == "host" else "Confirm::App"
                auto = "true" if rule["auto_approvable"] else "false"
                out.append(f"            ToolPolicy {{ tool: {s(tool)}, confirm: {confirm}, auto_approvable: {auto} }},")
            out.append("        ],")
        else:
            out.append("        tools: &[],")
        out.append("    },")
    out += [
        "];",
        "",
        "impl NativeApp {",
        "    /// Its hosting on the target this shell is built for.",
        "    pub const fn on_this_target(&self) -> Hosting {",
        "        if cfg!(target_arch = \"wasm32\") {",
        "            self.wasm",
        "        } else if cfg!(target_os = \"android\") {",
        "            self.android",
        "        } else if cfg!(target_os = \"ios\") {",
        "            self.ios",
        "        } else if cfg!(target_env = \"ohos\") {",
        "            self.ohos",
        "        } else if cfg!(target_os = \"macos\") {",
        "            self.macos",
        "        } else if cfg!(target_os = \"windows\") {",
        "            self.windows",
        "        } else {",
        "            self.linux",
        "        }",
        "    }",
        "}",
        "",
        "impl NativeApp {",
        "    /// The rule for one of its tools, if the manifest sets one.",
        "    pub fn tool(&self, name: &str) -> Option<&'static ToolPolicy> {",
        "        self.tools.iter().find(|rule| rule.tool == name)",
        "    }",
        "}",
        "",
        "/// The manifest entry for an app id.",
        "pub fn find(id: &str) -> Option<&'static NativeApp> {",
        "    APPS.iter().find(|app| app.id == id)",
        "}",
        "",
        "/// Push the native modules this build links, in manifest order.",
        "#[allow(unused_variables)]",
        "pub fn link(out: &mut Vec<&'static dyn AppModule>) {",
    ]
    for app in apps:
        feature = f"feature = {s(feature_of(app))}"
        cfg = f"any({feature}, native_mobile)" if app["native_mobile"] == "always" else feature
        modules = modules_of(app)
        out.append(f"    #[cfg({cfg})]")
        if len(modules) == 1:
            out.append(f"    out.push(&{modules[0]});")
        else:
            out.append("    {")
            out += [f"        out.push(&{m});" for m in modules]
            out.append("    }")
    out += ["}", ""]
    return "\n".join(out)


# --- Marked blocks ---------------------------------------------------------


def begin_marker(name):
    return f"# BEGIN native-apps: {name} {NOTE}"


def end_marker(name):
    return f"# END native-apps: {name}"


def replace_blocks(text, blocks, label):
    """`text` with each named block's lines between its markers replaced."""
    lines = text.split("\n")
    for name, body in blocks.items():
        begin, end = begin_marker(name), end_marker(name)
        starts = [i for i, line in enumerate(lines) if line.strip() == begin]
        ends = [i for i, line in enumerate(lines) if line.strip() == end]
        if len(starts) != 1 or len(ends) != 1 or ends[0] < starts[0]:
            raise ManifestError(f"{label}: needs exactly one '{begin}' ... '{end}' block")
        lines[starts[0] + 1:ends[0]] = body
    marked = re.findall(r"^\s*# BEGIN native-apps: (.*?) \(generated", text, re.M)
    for name in marked:
        if name not in blocks:
            raise ManifestError(f"{label}: block '{name}' has no source in {MANIFEST} (remove its markers)")
    return "\n".join(lines)


def workspace_pins(text):
    """(crate, git, rev) of each git pin in [workspace.dependencies]."""
    pins, table = [], None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("["):
            table = stripped
            continue
        if table != "[workspace.dependencies]":
            continue
        match = re.match(r"([A-Za-z0-9_-]+)\s*=\s*\{(.*)\}", stripped)
        if not match:
            continue
        git = re.search(r'\bgit\s*=\s*"([^"]+)"', match.group(2))
        rev = re.search(r'\brev\s*=\s*"([^"]+)"', match.group(2))
        if git and rev:
            pins.append((match.group(1), git.group(1), rev.group(1)))
    return pins


def check_one_revision(apps, text):
    """Each git repository an app comes from is pinned at one revision."""
    problems = []
    for app in apps:
        source = app["source"]
        if "git" not in source:
            continue
        for crate, git, rev in workspace_pins(text):
            if same_git(git, source["git"]) and rev != source["rev"]:
                problems.append(f"{crate} pins {git} at {rev[:12]}, {app['id']} at {source['rev'][:12]}")
    if problems:
        raise ManifestError("Cargo.toml: one revision per repository:\n  " + "\n  ".join(sorted(set(problems))))


def generate(root):
    """{relative path: (current text or None, generated text)}."""
    root = Path(root)
    apps = load(root)

    def read(rel):
        path = root / rel
        return path.read_text() if path.is_file() else None

    out = {}
    text = read("Cargo.toml")
    if text is None:
        raise ManifestError("Cargo.toml is missing")
    new = replace_blocks(text, root_blocks(apps), "Cargo.toml")
    check_one_revision(apps, new)
    out["Cargo.toml"] = (text, new)
    rel = "crates/shell/Cargo.toml"
    text = read(rel)
    if text is None:
        raise ManifestError(f"{rel} is missing")
    out[rel] = (text, replace_blocks(text, shell_blocks(apps), rel))
    for shell, rel in PACKAGES.items():
        text = read(rel)
        if text is None:
            raise ManifestError(f"{rel} is missing")
        out[rel] = (text, replace_blocks(text, package_block(apps, shell, text), rel))
    out[RUST_FILE] = (read(RUST_FILE), render_rust(apps))
    return out


def changed_pins(old, new):
    """Crates whose pin in [workspace.dependencies] changed (not added)."""
    def pins(text):
        found, table = {}, None
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("["):
                table = stripped
                continue
            match = re.match(r"([A-Za-z0-9_-]+)\s*=", stripped)
            if table == "[workspace.dependencies]" and match:
                found[match.group(1)] = stripped
        return found
    before, after = pins(old), pins(new)
    return sorted(c for c in before if c in after and before[c] != after[c])


def update_lock(root, crates, cargo="cargo"):
    for crate in crates:
        note(f"cargo update -p {crate}")
        subprocess.run([cargo, "update", "-p", crate], cwd=root, check=True)
    note("cargo metadata (settles Cargo.lock)")
    subprocess.run([cargo, "metadata", "--format-version", "1"], cwd=root, check=True, stdout=subprocess.DEVNULL)


def main(argv=None, root=ROOT):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="change nothing; exit 1 when a generated place drifted")
    parser.add_argument("--no-lock", action="store_true", help="do not run cargo to update Cargo.lock")
    args = parser.parse_args(argv)
    try:
        results = generate(root)
    except ManifestError as error:
        print(f"native-apps: {error}", file=sys.stderr)
        return 2
    drifted = [rel for rel, (old, new) in results.items() if old != new]
    if args.check:
        for rel in drifted:
            print(f"::error::{rel} is not what native-apps.json generates; run python3 tools/native_apps.py")
        if not drifted:
            note("every generated place matches native-apps.json")
        return 1 if drifted else 0
    for rel in drifted:
        (Path(root) / rel).write_text(results[rel][1])
        note(f"wrote {rel}")
    if not drifted:
        note("nothing to do")
    toml_changed = any(rel.endswith("Cargo.toml") for rel in drifted)
    if toml_changed and not args.no_lock:
        old, new = results["Cargo.toml"]
        update_lock(root, changed_pins(old, new))
    return 0


if __name__ == "__main__":
    sys.exit(main())
